Feature/output schema tables
milk531/amplify-ds pull request #3
Opened 2023-02-24 09:48 UTC by homekuanyi

2023-02-25 14:39 UTC, milk531 requested changes
1. `scheme` 命令可以参考`example`或`export`命令进行改造，读取通用配置里的graphql文件。
2.  `validate`单独命令似乎必要性不高，命令执行时已经回检查token是否有效和对错误进行报错提示。

2023-02-25 14:39 UTC, milk531 commented on index.js
> +                let content = fs.readFileSync(`${process.cwd()}/src/models/schema.js`).toString();
js文件不是所有项目都存在的，请参考example命令的实现方式来重构一下这个导出所有table的命令

2023-02-25 14:39 UTC, milk531 commented on index.js
> +            case 'validate':
必要性似乎不是很大，每个需要token的操作会进行有效性检查，无效会输出日志

2023-02-26 07:22 UTC, homekuanyi commented on index.js
> +                let content = fs.readFileSync(`${process.cwd()}/src/models/schema.js`).toString();
> js文件不是所有项目都存在的，请参考example命令的实现方式来重构一下这个导出所有table的命令

已改为从shema.graphql读取重新实现

2023-02-26 07:28 UTC, homekuanyi commented on index.js
> +            case 'validate':
虽然每个操作都有有效性检查，实际使用场景在上传前都有耗时的前置操作，比如生成预览封面、预览视频、视频压缩转码、封面统一格式、模板素材制作；运营的需求希望能一次性跑完批量操作，然后就可以做其他事情或休息，不想中途被停止

2023-02-26 07:30 UTC, homekuanyi commented
> 1. `scheme` 命令可以参考`example`或`export`命令进行改造，读取通用配置里的graphql文件。
> 2. `validate`单独命令似乎必要性不高，命令执行时已经回检查token是否有效和对错误进行报错提示。

1. 已经做了修改
2. 是为了方便运营操作，提前知道token方便运营安排批量任务

2023-02-27 07:35 UTC, milk531 approved these changes
ok,可以吧当前main最新的内容merge到当前pr再提交一次即可

2023-02-27 07:47 UTC, merged